<a href="https://colab.research.google.com/github/Sanjana-Sarma/NTTF_Training/blob/main/DL_Class_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
from sklearn.cluster import KMeans

In [63]:
X=np.array([[11,2,3],[1,4,2],[1,0,3],[10,2,4],[9,4,3],[11,0,2]])

In [64]:
kmeans=KMeans(n_clusters=2, random_state=42).fit(X)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [65]:
print(kmeans.labels_)

[0 1 1 0 0 0]


In [66]:
print(kmeans.cluster_centers_)

[[10.25  2.    3.  ]
 [ 1.    2.    2.5 ]]


In [67]:
print(kmeans.predict([[12,3,1]]))

[0]


In [68]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.semi_supervised import LabelSpreading
from sklearn.datasets import make_circles

In [69]:
X=np.array([[0,1],[1,1],[2,0],[3,1],[10,5],[11,6],[12,4],[13,5]])
y=np.array([0,0,0,0,1,1,1,1])

In [70]:
labels=np.full(8,-1.)
labels[0]=0
labels[-1]=1
print(labels)

[ 0. -1. -1. -1. -1. -1. -1.  1.]


In [71]:
label_spread=LabelSpreading(kernel='knn', alpha=0.8)
label_spread.fit(X, labels)
output_label=label_spread.transduction_
print(output_label)

[0. 0. 0. 0. 1. 1. 1. 1.]


In [76]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing import image
from keras.applications.imagenet_utils import decode_predictions
import numpy as np
from tensorflow.keras.applications import(vgg16,resnet50,mobilenet_v2,inception_v3,efficientnet)

In [77]:
model=efficientnet.EfficientNetB0(weights='imagenet')
print(model.summary())

21834768/21834768 [==============================] - 0s 0us/step
Model: "efficientnetb0"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 224, 224, 3)]        0         []                            
                                                                                                  
 rescaling (Rescaling)       (None, 224, 224, 3)          0         ['input_1[0][0]']             
                                                                                                  
 normalization (Normalizati  (None, 224, 224, 3)          7         ['rescaling[0][0]']           
 on)                                                                                              
                                                                                                  
 rescaling_1 (Rescal