<a href="https://colab.research.google.com/github/Sanjana-Sarma/NTTF_Training/blob/main/Python_Class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

frame1 = pd.DataFrame({'ID':['ball', 'pencil', 'pen', 'eraser', 'mug'], 'price':['20.54', '2.32', '1.50', '4.50', '60.34']})
frame1


ID  price
0    ball  20.54
1  pencil   2.32
2     pen   1.50
3  eraser   4.50
4     mug  60.34

In [ ]:
frame2 = pd.DataFrame({'ID':['ball', 'pencil', 'mug', 'rose'], 'Colour':['blue', 'brown', 'white', 'red']})
frame2

ID Colour
0    ball   blue
1  pencil  brown
2     mug  white
3    rose    red

In [ ]:
pd.merge(frame1, frame2)

ID  price Colour
0    ball  20.54   blue
1  pencil   2.32  brown
2     mug  60.34  white

In [ ]:
frame1 = pd.DataFrame({'ID':["ball", 'pencil', 'pen', 'eraser', 'mug'],
                       'Price':['20.20', '2.50', '10.50', '5.00', '30.20'],
                       'Colour':['blue', 'brown', 'blue', 'white', 'orange']})
frame1

ID  Price  Colour
0    ball  20.20    blue
1  pencil   2.50   brown
2     pen  10.50    blue
3  eraser   5.00   white
4     mug  30.20  orange

In [ ]:
frame2 = pd.DataFrame({'ID':['pencil', 'pen', 'ball', 'mug'],
                       'brand':['UFH', 'FMF', 'FHCJ', 'FHD']})
frame2

ID brand
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
pd.merge(frame1, frame2)

ID  Price  Colour brand
0    ball  20.20    blue  FHCJ
1  pencil   2.50   brown   UFH
2     pen  10.50    blue   FMF
3     mug  30.20  orange   FHD

In [ ]:
pd.merge(frame1, frame2, on = 'ID')

ID  Price  Colour brand
0    ball  20.20    blue  FHCJ
1  pencil   2.50   brown   UFH
2     pen  10.50    blue   FMF
3     mug  30.20  orange   FHD

In [ ]:
frame2

ID brand
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
frame2.columns = ['brand', 'sid']
frame2

brand   sid
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
pd.merge(frame1, frame2, left_on = 'ID', right_on = 'sid')

Empty DataFrame
Columns: [ID, Price, Colour, brand, sid]
Index: []

In [ ]:
frame2.columns = ['brand', 'ID']
frame2

brand    ID
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
pd.merge(frame1, frame2, on = 'ID', how = 'outer')

ID  Price  Colour   brand
0    ball  20.20    blue     NaN
1  pencil   2.50   brown     NaN
2     pen  10.50    blue     NaN
3  eraser   5.00   white     NaN
4     mug  30.20  orange     NaN
5     UFH    NaN     NaN  pencil
6     FMF    NaN     NaN     pen
7    FHCJ    NaN     NaN    ball
8     FHD    NaN     NaN     mug

In [ ]:
pd.merge(frame1, frame2, on = ['ID','brand'], how = 'outer')

KeyError: ignored

In [ ]:
frame2.columns = ['ID', 'brand']
frame2

ID brand
0  pencil   UFH
1     pen   FMF
2    ball  FHCJ
3     mug   FHD

In [ ]:
array1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
array2 = array1 + 6
result_array = np.concatenate([array1, array2], axis = 0)
result_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array2

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
ser1 = pd.Series(np.random.rand(4), index = [1, 2, 3, 4])
ser1

1    0.866347
2    0.851754
3    0.561155
4    0.175049
dtype: float64

In [ ]:
ser2 = pd.Series(np.random.rand(4), index = [5, 6, 7, 8])
ser2

5    0.824394
6    0.495098
7    0.664755
8    0.401829
dtype: float64

In [ ]:
pd.concat([ser1, ser2])

1    0.866347
2    0.851754
3    0.561155
4    0.175049
5    0.824394
6    0.495098
7    0.664755
8    0.401829
dtype: float64

In [ ]:
pd.concat([ser1, ser2], axis = 1)

0         1
1  0.866347       NaN
2  0.851754       NaN
3  0.561155       NaN
4  0.175049       NaN
5       NaN  0.824394
6       NaN  0.495098
7       NaN  0.664755
8       NaN  0.401829

In [ ]:
pd.concat([ser1, ser2], keys=[1,2])

1  1    0.866347
   2    0.851754
   3    0.561155
   4    0.175049
2  5    0.824394
   6    0.495098
   7    0.664755
   8    0.401829
dtype: float64

In [ ]:
pd.concat([ser1, ser2], keys=[1,2], axis=1)

1         2
1  0.866347       NaN
2  0.851754       NaN
3  0.561155       NaN
4  0.175049       NaN
5       NaN  0.824394
6       NaN  0.495098
7       NaN  0.664755
8       NaN  0.401829

In [ ]:
ser1 = pd.Series(np.random.rand(5), index=['1','2','3','4','5'])
ser1

1    0.273645
2    0.337393
3    0.585270
4    0.776960
5    0.107211
dtype: float64

In [ ]:
ser2 = pd.Series(np.random.rand(4), index = ['5','6','7','8'])
ser2

5    0.944235
6    0.550051
7    0.133215
8    0.824091
dtype: float64

In [ ]:
ser1.combine_first(ser2)

1    0.273645
2    0.337393
3    0.585270
4    0.776960
5    0.107211
6    0.550051
7    0.133215
8    0.824091
dtype: float64

In [ ]:
ser2.combine_first(ser1)

1    0.273645
2    0.337393
3    0.585270
4    0.776960
5    0.944235
6    0.550051
7    0.133215
8    0.824091
dtype: float64

In [ ]:
ser1[:3].combine_first(ser2[:3])

1    0.273645
2    0.337393
3    0.585270
5    0.944235
6    0.550051
7    0.133215
dtype: float64

In [ ]:
results = [12,34,19,35,67,35,89,24,38,89,12,54,25,45,54,25,65,77,88,99]
bins = [0,25,50,75,100]
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (0, 25], (25, 50], (50, 75], ..., (0, 25], (50, 75], (75, 100], (75, 100], (75, 100]]
Length: 20
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [ ]:
cat.categories


IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]], dtype='interval[int64, right]')

In [ ]:
cat.codes

array([0, 1, 0, 1, 2, 1, 3, 0, 1, 3, 0, 2, 0, 1, 2, 0, 2, 3, 3, 3],
      dtype=int8)

In [ ]:
pd.value_counts(cat)

(0, 25]      6
(25, 50]     5
(75, 100]    5
(50, 75]     4
dtype: int64

In [ ]:
rand_data = pd.DataFrame({
    '1': np.random.rand(1000),
    '2': np.random.randn(1000),
    '3': np.random.randint(1, 100, size=1000)
})
rand_data

1         2   3
0    0.632616 -1.002687  73
1    0.534850 -0.171215  86
2    0.915402 -0.057286  34
3    0.627762  0.777882   1
4    0.127771  2.314212  43
..        ...       ...  ..
995  0.360964 -0.255618  71
996  0.672492 -0.103925  49
997  0.946354  0.407598  21
998  0.415400  0.448271  62
999  0.612391  0.846224  67

[1000 rows x 3 columns]

In [ ]:
rand_data.describe()

1            2            3
count  1000.000000  1000.000000  1000.000000
mean      0.487520     0.041991    50.307000
std       0.282863     0.988242    28.263078
min       0.000974    -3.945515     1.000000
25%       0.237545    -0.618146    26.000000
50%       0.491516     0.001787    50.500000
75%       0.721737     0.694288    74.000000
max       0.999865     3.153110    99.000000

In [ ]:
rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(1)]

<ipython-input-52-e2e5f25cf61e>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(1)]


1         2   3
1    0.534850 -0.171215  86
2    0.915402 -0.057286  34
7    0.954874 -1.283914  38
11   0.937071  1.107053   6
12   0.954414  0.594142  29
..        ...       ...  ..
980  0.647956 -1.673829  94
982  0.068824  1.016152  94
991  0.330812 -1.422969  93
994  0.916281  0.862993  25
997  0.946354  0.407598  21

[262 rows x 3 columns]

In [ ]:
rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(2)]

<ipython-input-51-b8b81a0e329f>:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  rand_data[(np.abs(rand_data)>(3*rand_data.std())).any(2)]


ValueError: ignored